version: "3"
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tutor-matcher-frontend
    ports:
      - "5173:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes:
      - ./dist:/usr/share/nginx/html