services:
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - 5672:5672
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=admin
  resource-mysql:
    image: mysql:8
    container_name: resource-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=resource_service_db 
      - MYSQL_USER=sherlock
      - MYSQL_PASSWORD=elementary 
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  lesson-mysql:
    image: mysql:8
    container_name: lesson-mysql
    ports:
      - 3305:3306
    environment:
      - MYSQL_DATABASE=lesson_service_db
      - MYSQL_USER=sherlock
      - MYSQL_PASSWORD=elementary
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  user-postgres:
    image: postgres
    container_name: user-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123
  calendar-postgres:
    image: postgres
    container_name: calendar-postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=123
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
  calendar-service:
    image: calendar-service
    container_name: calendar-service
#    ports:
#      - 8081:8080
    depends_on:
    - consul
    - calendar-postgres
  lesson-service:
    image: lesson-service
    container_name: lesson-service
    environment:
      - JDBC_HOST=host.docker.internal
      - JDBC_PORT=3305
    restart: always
#    ports:
#      - 8082:8080
    depends_on:
    - consul
    - lesson-mysql
  matcher-service:
    image: matcher-service
    container_name: matcher-service
#    ports:
#      - 8083:8080
  resource-service:
    image: resource-service
    container_name: resource-service
    environment:
      - JDBC_HOST=host.docker.internal
      - JDBC_PORT=3306
#    ports:
#      - 8085:8080
    depends_on:
    - consul
    - resource-mysql
    restart: always
  user-service:
    image: user-service
    container_name: user-service
#    ports:
#      - 8086:8080
    depends_on:
    - consul
    - user-postgres
  api-gw:
    image: api-gw
    container_name: api-gw
    ports:
      - 8080:8080
    



