DROP TABLE IF EXISTS resources;

CREATE TABLE resource (
    id   BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
   username  VARCHAR(255) NOT NULL,
   type VARCHAR(255) NOT NULL,
   name  VARCHAR(255) NOT NULL,
   description  VARCHAR(255),
   resource_url  VARCHAR(255) NOT NULL UNIQUE
);